name: improved_kd
defaults:
    - annealer@params.annealer: constant
    - optimizer@params.optimizer: adam
    - lr_scheduler@params.lr_scheduler: constant
params:
    alpha: 0.1
    focal: all
    eta: 1.0
    warm_start: False