experiment_name: cold_start
defaults:
    - callbacks: default
    - data: mnist
    - misc: default
    - model: lenet
    - lightning_module@orig_module: standard
    - lightning_module@new_module: standard
    - trainer: default
hydra:
    run:
        dir: results/${data.name}/${model.name}/${experiment_name}/${wandb_run:}
    output_subdir: .