experiment_name: ensemble_offline
data_name: mnist
model_name: lenet
random_state: null
num_models: 3
hydra:
    run:
        dir: results/${data_name}/${model_name}/${experiment_name}/${wandb_run:}
    output_subdir: .