experiment_name: low_curvature
epochs: 100
log_frequency: 10
lr: 0.01
num_samples: 1000
optimizer: sgd
defaults:
    - data: mnist
    - gradient_projector: identity # null, linprog, or hessian
    - loss: ce
    - misc: default
    - model: lenet1
hydra:
    run:
        dir: results/low_curvature/${wandb_run:}
    output_subdir: .