experiment_name: pc_training
defaults:
    - callbacks: default
    - data: mnist
    - misc: default
    - model: lenet
    - lightning_module@orig_module: standard
    - lightning_module@distill_module: pc_training
    - trainer@orig_trainer: default
    - trainer@distill_trainer: default
hydra:
    run:
        dir: results/${data.name}/${model.name}/pc_training/${distill_module.params.alpha}/${misc.seed}
    output_subdir: .