experiment_name: projection
defaults:
    - callbacks: default
    - data: mnist
    - misc: default
    - model: lenet
    - lightning_module@orig_module: standard
    - lightning_module@projection_module: projection
    - trainer: default
hydra:
    run:
        dir: results/${data.name}/${model.name}/ogd/${misc.seed}
    output_subdir: .