experiment_name: stack_and_distill
alpha: 0.5
data_name: mnist
model_name: lenet
random_state: null
normalize: False
num_layers: 1
seed: 0
hydra:
    run:
        dir: results/${data_name}/${model_name}/${experiment_name}/${wandb_run:}
    output_subdir: .