experiment_name: warm_start
defaults:
    - callbacks: default
    - data: mnist
    - misc: default
    - model: lenet
    - lightning_module@orig_module: standard
    - lightning_module@warm_module: standard
    - trainer: default
hydra:
    run:
        dir: results/${data.name}/${model.name}/warm_start/${misc.seed}
    output_subdir: .